/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cooptransporte;

import clases.venta;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class DetalleBoleto extends javax.swing.JInternalFrame {

    /**
     * Creates new form DetalleBoleto
     */
    
    venta v = new venta();
    
    
    public DetalleBoleto() {
        initComponents();
    }
    
    public void cargarVentasAsiento(String bus, String asiento) {
        String archivoVentas = "datos/ventas.csv";  // Verifica que la ruta sea correcta
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoVentas))) {
            String linea;
            int encontro = 0;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Dividir por coma
                if(datos[4].equals(bus) && datos[3].equals(asiento)){
                    encontro = 1;
                    v.setNombrePasajero(datos[0]);     // Cliente
                    v.setApellidoPasajero(datos[1]);     // Asiento
                    v.setRutaDestino(datos[2]);   // Número de Bus
                    v.setNumeroAsiento(datos[3]); // Número de Venta
                    v.setNumeroBus(datos[4]);
                    v.setFechaViaje(datos[5]);
                    v.setHoraViaje(datos[6]);
                    v.setPrecioBoleto(datos[7]);
                }
                // Verificar que hay exactamente 7 elementos en cada línea     
            }
            if(encontro == 1){
                llenarInformacion();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al leer el archivo de ventas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    public void cargarVentasCliente(String cliente) {
        String archivoVentas = "datos/ventas.csv";  // Verifica que la ruta sea correcta
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoVentas))) {
            String linea;
            int encontro = 0;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Dividir por coma
                String cl_guardado = datos[1]+" "+datos[0];
                System.out.println(cl_guardado.trim()+"||"+cliente.trim());
                if(cl_guardado.trim().equals(cliente.trim())){
                    encontro = 1;
                    v.setNombrePasajero(datos[0]);     // Cliente
                    v.setApellidoPasajero(datos[1]);     // Asiento
                    v.setRutaDestino(datos[2]);   // Número de Bus
                    v.setNumeroAsiento(datos[3]); // Número de Venta
                    v.setNumeroBus(datos[4]);
                    v.setFechaViaje(datos[5]);
                    v.setHoraViaje(datos[6]);
                    v.setPrecioBoleto(datos[7]);
                }
                // Verificar que hay exactamente 7 elementos en cada línea     
            }
            if(encontro == 1){
                llenarInformacion();
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al leer el archivo de ventas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void llenarInformacion(){
        cliente.setText(v.getApellidoPasajero()+" "+v.getNombrePasajero());
        busAsiento.setText("Bus: "+v.getNumeroBus()+" || Asiento: #"+v.getNumeroAsiento());
        Fecha.setText("Fecha: "+v.getFechaViaje()+" || Hora: "+v.getHoraViaje());
        Destino.setText("Destino: "+v.getRutaDestino());
        precio.setText("$"+v.getPrecioBoleto());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        busAsiento = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Destino = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Detalle de Boleto");

        cliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cliente.setText("No Existe Registro");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("INFORMACION DE BOLETO");

        busAsiento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        busAsiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busAsiento.setText("-");

        Fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fecha.setText("-");

        Destino.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Destino.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Destino.setText("-");

        precio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        precio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio.setText("-");

        precio1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        precio1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        precio1.setText("Cooperativa REALES TAMARINDOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(busAsiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Destino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precio1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(cliente)
                .addGap(18, 18, 18)
                .addComponent(busAsiento)
                .addGap(18, 18, 18)
                .addComponent(Fecha)
                .addGap(18, 18, 18)
                .addComponent(Destino)
                .addGap(18, 18, 18)
                .addComponent(precio)
                .addGap(18, 18, 18)
                .addComponent(precio1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Destino;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel busAsiento;
    private javax.swing.JLabel cliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precio1;
    // End of variables declaration//GEN-END:variables
}
