/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cooptransporte;

import interfaces.selecciona_boletos;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class verAsientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form verBuses
     */
    int bus;
    private selecciona_boletos listener;
    String[] columnas = {"Asiento", "Estado"};
    DefaultTableModel modelo = new DefaultTableModel(null, columnas){
            public boolean isCellEditable(int row, int column) {
                return false; // Ninguna celda será editable
            }
        };
    
    

    public void setListener(selecciona_boletos listener) {
        this.listener = listener;  // Asignar la instancia de VentanaDestino
    }

    public JButton getSeleccionar() {
        return seleccionar;
    }

    public void setSeleccionar(JButton seleccionar) {
        this.seleccionar = seleccionar;
    }

    public int getBus() {
        return bus;
    }

    public void setBus(int bus) {
        this.bus = bus;
    }
    
    public void llenaModelo(){
        for (int i = 0; i < 50; i++) {
            modelo.addRow(new Object[]{i+1, "disponible"});
        }
        jTable1.setModel(modelo);
    }
    
    
    
    public verAsientos() {
        initComponents();
        for (int i = 0; i < 50; i++) {
            modelo.addRow(new Object[]{i+1, "disponible"});
        }
        jTable1.setModel(modelo);
        
    }
    
    
    
public void cargarDatos(String fecha) {
        // Definir el archivo CSV
        String archivo = "datos/ventas.csv";
        
        // Leer el archivo y cargar los datos en el modelo
        try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
            String linea;
            numBus.setText(String.valueOf(bus));
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Separar los datos por coma
                System.out.println("");
                if(datos[4].equals(String.valueOf(bus)) && datos[5].equals(fecha)){
                   int fila = buscarFilaPorId(datos[3]);
                    if(fila != -1){
                        modelo.setValueAt("ocupado", fila, 1);
                    }       
                }
                    
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }

        // Asignar el modelo a la JTable
        jTable1.setModel(modelo); // jTable1 es la tabla donde se cargarán los datos
}

public int buscarFilaPorId(String idBuscado) {
    for (int fila = 0; fila < modelo.getRowCount(); fila++) {
        Object valor = modelo.getValueAt(fila, 0); // Primera columna (ID)

        if (valor != null && valor.toString().equals(idBuscado)) {
            return fila; // Retorna el índice de la fila donde está el ID
        }
    }
    return -1; // Retorna -1 si no se encuentra el ID
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        seleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numBus = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Boletos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(361, 285));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMovimiento(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        seleccionar.setForeground(new java.awt.Color(255, 0, 0));
        seleccionar.setText("Seleccionar");
        seleccionar.setEnabled(false);
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Asientos del bus:");

        numBus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numBus.setForeground(new java.awt.Color(51, 51, 255));

        LocalDate fechaActual = LocalDate.now();
        Date date = Date.from(fechaActual.atStartOfDay(ZoneId.systemDefault()).toInstant());
        fecha.setDate(date);
        fecha.setDateFormatString("dd-MM-yyyy");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numBus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        int fila = jTable1.getSelectedRow();
        if(fila != -1){
            String valor = jTable1.getValueAt(fila, 0).toString();
            if (listener != null) {
                if(jTable1.getValueAt(fila, 1).toString().equals("disponible")){
                    listener.recibirBoletos(valor); // Pasar el valor a la interfaz
                    this.dispose();
                }else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Este asiento ya se encuentra ocupado");
                }          
            }
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void noMovimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMovimiento
        // TODO add your handling code here:
    }//GEN-LAST:event_noMovimiento

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(fecha.getDate() != null){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String fechaBusca = sdf.format(fecha.getDate());
            System.out.println(fechaBusca);
            modelo.setRowCount(0);
            llenaModelo();
            cargarDatos(fechaBusca);
        }else{
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fecha valida");  
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numBus;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
