/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cooptransporte;

import interfaces.selecciona_boletos;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class verAsientos extends javax.swing.JInternalFrame {

    /**
     * Creates new form verBuses
     */
    int bus;
    private selecciona_boletos listener;

    public void setListener(selecciona_boletos listener) {
        this.listener = listener;  // Asignar la instancia de VentanaDestino
    }

    public JButton getSeleccionar() {
        return seleccionar;
    }

    public void setSeleccionar(JButton seleccionar) {
        this.seleccionar = seleccionar;
    }

    public int getBus() {
        return bus;
    }

    public void setBus(int bus) {
        this.bus = bus;
    }
    
    
    
    public verAsientos() {
        initComponents();
    }
    
    
    
public void cargarDatos() {
        // Definir el archivo CSV
        String archivo = "datos/boletos.csv";

        // Crear el modelo de la tabla con las columnas ya definidas
        String[] columnas = {"Asiento", "Estado"}; // Las columnas que ya tienes establecidas
        DefaultTableModel modelo = new DefaultTableModel(null, columnas){
            public boolean isCellEditable(int row, int column) {
                return false; // Ninguna celda será editable
            }
        };
        
        // Leer el archivo y cargar los datos en el modelo
        try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
            String linea;
            numBus.setText(String.valueOf(bus));
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Separar los datos por coma
                
                    if(Integer.parseInt(datos[0]) == bus){
                        modelo.addRow(new Object[]{datos[1], datos[2]});
                    }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }

        // Asignar el modelo a la JTable
        jTable1.setModel(modelo); // jTable1 es la tabla donde se cargarán los datos
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        seleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numBus = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Lista de Boletos");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(336, 270));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noMovimiento(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        seleccionar.setForeground(new java.awt.Color(255, 0, 0));
        seleccionar.setText("Seleccionar");
        seleccionar.setEnabled(false);
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Asientos del bus:");

        numBus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        numBus.setForeground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(193, Short.MAX_VALUE)
                        .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numBus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        int fila = jTable1.getSelectedRow();
        if(fila != -1){
            String valor = jTable1.getValueAt(fila, 0).toString();
            if (listener != null) {
                listener.recibirBoletos(valor); // Pasar el valor a la interfaz
                this.dispose();
            } else {
                System.out.println("Error: El listener no ha sido asignado.");
            }
        }else{
            System.out.println("Ninguna fila seleccionada");
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void noMovimiento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noMovimiento
        // TODO add your handling code here:
    }//GEN-LAST:event_noMovimiento


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel numBus;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
