/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cooptransporte;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import javax.swing.JDesktopPane;

/**
 *
 * @author user
 */
public class verBuses extends javax.swing.JInternalFrame {

    /**
     * Creates new form verBuses
     */
    
    JDesktopPane pr;

    public JDesktopPane getPr() {
        return pr;
    }

    public void setPr(JDesktopPane pr) {
        this.pr = pr;
    }
    
    
    
    public verBuses() {
        initComponents();
    }
    
public void cargarDatos() {
        // Definir el archivo CSV
        String archivo = "datos/buses.csv";

        // Crear el modelo de la tabla con las columnas ya definidas
        String[] columnas = {"Número de Bus", "Estado"}; // Las columnas que ya tienes establecidas
        DefaultTableModel modelo = new DefaultTableModel(null, columnas){
            public boolean isCellEditable(int row, int column) {
                return false; // Ninguna celda será editable
            }
        };
        
        // Leer el archivo y cargar los datos en el modelo
        try (BufferedReader reader = new BufferedReader(new FileReader(archivo))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Separar los datos por coma

                    modelo.addRow(new Object[]{datos[0], datos[1]});
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo: " + e.getMessage());
        }

        // Asignar el modelo a la JTable
        jTable1.setModel(modelo); // jTable1 es la tabla donde se cargarán los datos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Buses");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(336, 240));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        seleccionar.setForeground(new java.awt.Color(255, 0, 0));
        seleccionar.setText("Seleccionar");
        seleccionar.setEnabled(false);
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(seleccionar)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // Validar que se haya seleccionado una fila
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            // Obtener el número de bus y el estado de la fila seleccionada
            String numeroBus = jTable1.getValueAt(fila, 0).toString();
            String estadoBus = jTable1.getValueAt(fila, 1).toString();

            switch (estadoBus) {
                case "disponible":
                    // Proceder con la eliminación directa
                    eliminarBusYAsientos(numeroBus);
                    javax.swing.JOptionPane.showMessageDialog(
                        this, 
                        "Bus y boletos eliminados correctamente."
                    );
                    break;

                case "reservado":
                    // Mostrar advertencia antes de eliminar
                    int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "¿Está seguro de eliminar este bus? Los boletos vendidos serán cancelados inmediatamente.",
                        "Confirmar eliminación",
                        javax.swing.JOptionPane.YES_NO_OPTION
                    );

                    if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                        eliminarBusYAsientos(numeroBus);
                        javax.swing.JOptionPane.showMessageDialog(
                            this, 
                            "Bus y boletos eliminados correctamente."
                        );
                    }
                    break;

                case "ocupado":
                    // Mostrar mensaje de error
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Imposible eliminar el bus. Por favor, libere los asientos primero.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                    );
                    break;

                default:
                    // Caso inesperado
                    javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Estado desconocido. Por favor, revise los datos.",
                        "Advertencia",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                    );
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Debe seleccionar un bus para eliminar.", 
                "Advertencia", 
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }

    // Método auxiliar para eliminar bus y sus asientos relacionados
    private void eliminarBusYAsientos(String numeroBus) {
        // Ruta de los archivos CSV
        String archivoBuses = "datos/buses.csv";
        String archivoBoletos = "datos/boletos.csv";

        // **1. Eliminar el bus del archivo buses.csv**
        StringBuilder contenidoActualizadoBuses = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoBuses))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(",");
                if (!datos[0].equals(numeroBus)) { // Excluir el bus seleccionado
                    contenidoActualizadoBuses.append(linea).append("\n");
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo buses.csv: " + e.getMessage());
        }

        try (java.io.FileWriter writer = new java.io.FileWriter(archivoBuses)) {
            writer.write(contenidoActualizadoBuses.toString());
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo buses.csv: " + e.getMessage());
        }

        // **2. Eliminar los asientos relacionados del archivo boletos.csv**
        StringBuilder contenidoActualizadoBoletos = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoBoletos))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(",");
                if (!datos[0].equals(numeroBus)) { // Excluir boletos del bus seleccionado
                    contenidoActualizadoBoletos.append(linea).append("\n");
                }
            }
        } catch (IOException e) {
            System.err.println("Error al leer el archivo boletos.csv: " + e.getMessage());
        }

        try (java.io.FileWriter writer = new java.io.FileWriter(archivoBoletos)) {
            writer.write(contenidoActualizadoBoletos.toString());
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo boletos.csv: " + e.getMessage());
        }

        // **3. Recargar los datos en la tabla**
        cargarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            Object valor = jTable1.getValueAt(fila, 0); // 0 es la primera columna
            verAsientos va = new verAsientos();
            va.setBus(Integer.parseInt((String) valor));
            va.cargarDatos();
            pr.moveToFront(va); // Mueve al frente
            pr.add(va, javax.swing.JDesktopPane.PALETTE_LAYER);
            System.out.println("Se abrira la ventana");
            va.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton seleccionar;
    // End of variables declaration//GEN-END:variables
}
