/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cooptransporte;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;

/**
 *
 * @author user
 */
public class verVentas extends javax.swing.JInternalFrame {
    
   


    /**
     * Creates new form verVentas
     */
    public verVentas() {
        initComponents();
        cargarVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setTitle("Boletos Vendidos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[]{"Nombre", "Cliente", "Destino", "Asiento", "Bus", "Fecha", "Hora", "Precio"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas NO son editables
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // Método para cargar los boletos vendidos desde boletos.csv
        private void cargarVentas() {
        String archivoVentas = "datos/ventas.csv";  // Verifica que la ruta sea correcta
        try (BufferedReader reader = new BufferedReader(new FileReader(archivoVentas))) {
            String linea;
            while ((linea = reader.readLine()) != null) {
                String[] datos = linea.split(","); // Dividir por coma

                // Verificar que hay exactamente 7 elementos en cada línea
                    String nombre_cliente = datos[0];     // Cliente
                    String apellido_cliente = datos[1];     // Asiento
                    String ruta_destino = datos[2];   // Número de Bus
                    String numero_asiento = datos[3]; // Número de Venta
                    String numero_bus = datos[4];     // Destino
                    String fecha_viaje = datos[5];      // Precio
                    String hora_viaje = datos[6];
                    String precio_boleto = datos[7];

                    // Aquí se debe usar jTable1, ya que es el componente real
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel(
                    );
                    model.addRow(new Object[]{nombre_cliente, apellido_cliente, ruta_destino, numero_asiento, numero_bus, fecha_viaje, hora_viaje, precio_boleto});
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(
                this,
                "Error al leer el archivo de ventas: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
